// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Board extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private DigitalInput limitSwitchOn1;
private DigitalInput limitSwitchOn2;
private DigitalInput limitSwitchOn3;
private DigitalInput limitSwitchOn4;
private DigitalInput limitSwitchOn5;
private DigitalInput limitSwitchOn6;
private DigitalInput limitSwitchOn7;
private DigitalInput limitSwitchOn8;
private DigitalInput limitSwitchOn9;
private DigitalInput limitSwitchOn10;
private DigitalInput limitSwitchOn11;
private DigitalInput limitSwitchOn12;
private DigitalInput limitSwitchOn13;
private DigitalInput limitSwitchOn14;
private DigitalInput limitSwitchOn15;
private DigitalInput limitSwitchOn16;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Board() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
limitSwitchOn1 = new DigitalInput(0);
 addChild("LimitSwitchOn1", limitSwitchOn1);
 
 limitSwitchOn2 = new DigitalInput(1);
 addChild("LimitSwitchOn2", limitSwitchOn1);
 
 limitSwitchOn3 = new DigitalInput(2);
 addChild("LimitSwitchOn3", limitSwitchOn1);

 limitSwitchOn4 = new DigitalInput(3);
 addChild("LimitSwitchOn4", limitSwitchOn1);
 limitSwitchOn5 = new DigitalInput(4);
 addChild("LimitSwitchOn5", limitSwitchOn1);
 limitSwitchOn6 = new DigitalInput(5);
 addChild("LimitSwitchOn6", limitSwitchOn1);
 limitSwitchOn7 = new DigitalInput(6);
 addChild("LimitSwitchOn7", limitSwitchOn1);
 limitSwitchOn8 = new DigitalInput(7);
 addChild("LimitSwitchOn8", limitSwitchOn1);
 limitSwitchOn9 = new DigitalInput(8);
 addChild("LimitSwitchOn9", limitSwitchOn1);
 limitSwitchOn10 = new DigitalInput(9);
 addChild("LimitSwitchOn10", limitSwitchOn1);
 limitSwitchOn11 = new DigitalInput(10);
 addChild("LimitSwitchOn11", limitSwitchOn1);
 limitSwitchOn12 = new DigitalInput(11);
 addChild("LimitSwitchOn12", limitSwitchOn1);
 limitSwitchOn13 = new DigitalInput(12);
 addChild("LimitSwitchOn13", limitSwitchOn1);
 limitSwitchOn14 = new DigitalInput(13);
 addChild("LimitSwitchOn14", limitSwitchOn1);
 limitSwitchOn15 = new DigitalInput(14);
 addChild("LimitSwitchOn15", limitSwitchOn1);
 limitSwitchOn16 = new DigitalInput(15);
 addChild("LimitSwitchOn16", limitSwitchOn1);
 
 
 
 
 
 
 
 
 
 
 
 


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putBoolean("Limit Switch on 0", limitSwitchOn1.get());
        SmartDashboard.putBoolean("Limit Switch on 1", limitSwitchOn2.get());
        SmartDashboard.putBoolean("Limit Switch on 2", limitSwitchOn3.get());
        SmartDashboard.putBoolean("Limit Switch on 3", limitSwitchOn4.get());
        SmartDashboard.putBoolean("Limit Switch on 4", limitSwitchOn5.get());
        SmartDashboard.putBoolean("Limit Switch on 5", limitSwitchOn6.get());
        SmartDashboard.putBoolean("Limit Switch on 6", limitSwitchOn7.get());
        SmartDashboard.putBoolean("Limit Switch on 7", limitSwitchOn8.get());
        SmartDashboard.putBoolean("Limit Switch on 8", limitSwitchOn9.get());
        SmartDashboard.putBoolean("Limit Switch on 9", limitSwitchOn10.get());
        SmartDashboard.putBoolean("Limit Switch on 10", limitSwitchOn11.get());
        SmartDashboard.putBoolean("Limit Switch on 11", limitSwitchOn12.get());
        SmartDashboard.putBoolean("Limit Switch on 12", limitSwitchOn13.get());
        SmartDashboard.putBoolean("Limit Switch on 13", limitSwitchOn14.get());
        SmartDashboard.putBoolean("Limit Switch on 14", limitSwitchOn15.get());
        SmartDashboard.putBoolean("Limit Switch on 15", limitSwitchOn16.get());
        SmartDashboard.putBoolean("Limit Switch on 16", limitSwitchOn16.get());
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

